$kind: http-request
url: "{{BASE_URL}}/api/inventory/damage"
method: POST
headers:
  Authorization: Bearer {{ACCESS_TOKEN}}
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "assetId": "9513f5a2-7e1c-4f0e-8a88-c7589413acf5",
      "hall": "ZIA_HALL",
      "description": "The desk lamp is broken, unable to switch on"
    }
order: 5000
