$kind: http-request
url: "{{BASE_URL}}/api/admission/review/:id"
method: PATCH
headers:
  Authorization: Bearer {{ACCESS_TOKEN}}
  Content-Type: application/json
pathVariables:
  id: 1cdaddcd-419c-45e6-a1eb-4a813a445a5d
body:
  type: json
  content: |-
    {
      "status": "APPROVED"
    }
order: 4000
