$kind: http-request
url: "{{BASE_URL}}/api/inventory/assets"
method: POST
headers:
  Authorization: Bearer {{ACCESS_TOKEN}}
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "hall": "ZIA_HALL",
      "name": "Desk Lamp",
      "quantity": 5,
      "condition": "GOOD"
    }
order: 4000
