$kind: http-request
url: "{{BASE_URL}}/api/inventory/beds?hall=ZIA_HALL&roomId=32d520cd-8a5a-43ba-8\
  267-902d99b125f1&status=AVAILABLE"
method: GET
headers:
  Authorization: Bearer {{ACCESS_TOKEN}}
queryParams:
  hall: ZIA_HALL
  roomId: 32d520cd-8a5a-43ba-8267-902d99b125f1
  status: AVAILABLE
order: 3000
